name: Java CI with Maven
run-name: Workflow run by ${{github.actor}}
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
      - '**' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          run: mvn -B package --file pom.xml

  run-checkstyle:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Checkstyle for Java
        uses: dbelyaev/action-checkstyle@v1.16.6
